In [15]:
#Numpy의 ndarray의 데이터 선택을 위한 Indexing
import numpy as np

#단일 값 추출

array1 = np.arange(start = 1, stop = 10)
print('array1:',array1,'\n')

value = array1[2]
b_value = array1[-1]

print('value:',value,'b_value:',b_value,'\n')
print('type value: {}, b_value: {}\n'.format(type(value),type(b_value)))



#다차원 ndarray에서 단일 값 추출

array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print('array2d:\n')
print(array2d,'\n')

print('(row = 0, col = 0) index가 가르키는 값:', array2d[0, 0])
print('(row = 0, col = 1) index가 가르키는 값:', array2d[0, 1])
print('(row = 1, col = 0) index가 가르키는 값:', array2d[1, 0])
print('(row = 2, col = 2) index가 가르키는 값:', array2d[2, 2],'\n')


#Slicing을 통한 데이터 추출 ([:])
array2 = array1[0:3]
print('array1 slicing')
print(array2,'\n')

print('array2d slicing')
print('array2d[0:2, 0:2]\n',array2d[0:2, 0:2],'\n')
print('array2d[1:3, 0:3]\n',array2d[1:3, 0:3],'\n')
print('array2d[0:2, :]\n',array2d[0:2, :],'\n')
print('array2d[:, 0:2]\n',array2d[:, 0:2],'\n')
print('array2d[:, :]\n',array2d[:, :],'\n')
print('array2d[:3, :]\n',array2d[:3, :],'\n')
print('array2d[:, 1:]\n',array2d[:, 1:],'\n')

print('array2d\'s axis0 shape')
print('array2d[0]:',array2d[0])
print('array2d[1]:',array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:', array2d[1].shape)

array1: [1 2 3 4 5 6 7 8 9] 

value: 3 b_value: 9 

type value: <class 'numpy.int64'>, b_value: <class 'numpy.int64'>

array2d:

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

(row = 0, col = 0) index가 가르키는 값: 1
(row = 0, col = 1) index가 가르키는 값: 2
(row = 1, col = 0) index가 가르키는 값: 4
(row = 2, col = 2) index가 가르키는 값: 9 

array1 slicing
[1 2 3] 

array2d slicing
array2d[0:2, 0:2]
 [[1 2]
 [4 5]] 

array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]] 

array2d[0:2, :]
 [[1 2 3]
 [4 5 6]] 

array2d[:, 0:2]
 [[1 2]
 [4 5]
 [7 8]] 

array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[:3, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[:, 1:]
 [[2 3]
 [5 6]
 [8 9]] 

array2d's axis0 shape
array2d[0]: [1 2 3]
array2d[1]: [4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [16]:
#Fancy Indexing: list나 ndarray로 인덱스 집합을 지정하여, 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식 ([,])

array3 = array2d[[0,1],2] #팬시 인덱싱, 단일 값 인덱싱
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2] # 펜시 인덱싱, 슬라이싱 인덱싱
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>',array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [26]:
#Boolean Indexing: 조건 필터링과 검색을 동시에 할 수 있는 인덱싱 방식
boolean_array = array1d[array1d > 5]
print('array1d:',array1d)
print('array1d > 5 조건의 Boolean indexing 결과 값:',boolean_array,'\n')

boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
boolean_indexes_array = array1d[boolean_indexes]
print('boolean_indexes:',boolean_indexes.tolist())
print('boolean_indexes로 필터링한 결과:', boolean_indexes_array,'\n')

indexes = np.array([5,6,7,8])
array6 = array1d[indexes]
print('ndarray indexes:',indexes)
print('일반 ndarray 인덱스로 필터링한 결과:', array6,'\n')

n_indexes = [5,6,7,8]
array7 = array1d[n_indexes]
print('n_indexes:', n_indexes)
print('일반 리스트 인덱스로 필터링한 결과:',array7,'\n')

array1d: [1 2 3 4 5 6 7 8 9]
array1d > 5 조건의 Boolean indexing 결과 값: [6 7 8 9] 

boolean_indexes: [False, False, False, False, False, True, True, True, True]
boolean_indexes로 필터링한 결과: [6 7 8 9] 

ndarray indexes: [5 6 7 8]
일반 ndarray 인덱스로 필터링한 결과: [6 7 8 9] 

n_indexes: [5, 6, 7, 8]
일반 리스트 인덱스로 필터링한 결과: [6 7 8 9] 

