In [2]:
import numpy as np

#Sort, np.sort() & ndarray.sort()
"""
np.sort(): 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None

np.argsort(): 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
"""

org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array,'\n')

#1 np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort()를 통해 반환된 정렬 행렬:',sort_array1)
print('np.sort()를 호출한 후 원본 행렬:',org_array,'\n')

#2 ndarray.sort()로 정렬

sort_array2 = org_array.sort()
print('org_array.sort()를 통해 반환된 정렬 행렬:', sort_array2)
print('org_array.sort()를 호출한 후 원본 행렬:',org_array,'\n')

#3 np.sort()를 통한 내림차순 정렬
sort_array_desc = np.sort(org_array)[::-1]
print('내림차순 정렬 행렬:',sort_array_desc,'\n')

원본 행렬: [3 1 9 5] 

np.sort()를 통해 반환된 정렬 행렬: [1 3 5 9]
np.sort()를 호출한 후 원본 행렬: [3 1 9 5] 

org_array.sort()를 통해 반환된 정렬 행렬: None
org_array.sort()를 호출한 후 원본 행렬: [1 3 5 9] 

내림차순 정렬 행렬: [9 5 3 1] 



In [5]:
#2차원 이상의 행렬 정렬
array2d = np.array([[8,1],
                  [7,12]])
print('원본 행렬:',array2d,'\n')

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0,'\n')

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1,'\n')



원본 행렬: [[ 8  1]
 [ 7 12]] 

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]] 

칼럼 방향으로 정렬:
 [[ 1  8]
 [ 7 12]] 



In [8]:
#정렬된 행렬의 원본 행렬 원소에 대한 인덱스 반환 by np.argsort()

org_array2 = np.array([3,1,9,5])
sort_indices = np.argsort(org_array2)

print('원본 행렬:',org_array2,'\n')

print('np.argsort()를 통해 반환된 값의 타입:',type(sort_indices))
print('행렬 정렬 시 원본 행렬 원소의 인덱스:',sort_indices,'\n')

#np.argsort()를 통한 내림차순 정렬

sort_indices_desc = np.argsort(org_array2)[::-1]
print('행렬 역순 정렬 시 원본 행렬 원소의 인덱스:',sort_indices_desc)

원본 행렬: [3 1 9 5] 

np.argsort()를 통해 반환된 값의 타입: <class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬 원소의 인덱스: [1 0 3 2] 

행렬 역순 정렬 시 원본 행렬 원소의 인덱스: [2 3 0 1]


In [14]:
#np.argsort()의 활용 예제, np.argsort()를 통해 반환된 인덱스를 팬시 인덱스로 적용해 추출하는 방법

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

print('원본 name_array:',name_array)
print('원본 score_array:',score_array)

sort_indices_asc = np.argsort(score_array)
print('')
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순 index로 name_array 출력:',name_array[sort_indices_asc])
print('정렬된 성적 행렬 출력:', np.sort(score_array),'\n')



원본 name_array: ['John' 'Mike' 'Sarah' 'Kate' 'Samuel']
원본 score_array: [78 95 84 98 88]

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순 index로 name_array 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
정렬된 성적 행렬 출력: [78 84 88 95 98] 



In [16]:
#선형대수 연산 - 행렬의 내적과 전치 행렬 구하기

#1 행렬의 내적 == 행렬의 곱, np.dot() method를 통해 계산 가능
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:',dot_product,'\n')

#2 전치 행렬: 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬, np.transpose()를 통해 구할 수 있다.

C = np.array([[1,2],
             [3,4]])
D = np.array([[1,2],
             [3,4],
             [5,6]])

transpose_c = np.transpose(C)
transpose_d = np.transpose(D)

print('C의 원본 행렬:\n',C,'\n')
print('C의 전치 행렬:\n',transpose_c,'\n')
print('D의 원본 행렬:\n',D,'\n')
print('D의 전치 행렬:\n',transpose_d,'\n')



행렬 내적 결과: [[ 58  64]
 [139 154]] 

C의 원본 행렬:
 [[1 2]
 [3 4]] 

C의 전치 행렬:
 [[1 3]
 [2 4]] 

D의 원본 행렬:
 [[1 2]
 [3 4]
 [5 6]] 

D의 전치 행렬:
 [[1 3 5]
 [2 4 6]] 

