In [7]:
import numpy as np

#type(): numpy.ndarray와 같은 타입 형태 반환
#shape: tuple 형태로 차원과 크기 반환
array1 = np.array([1,2,3])
print('Array1 type:',type(array1))
print('Array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                 [2,3,4]])
print('Array2 type:',type(array2))
print('Array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('Array3 type:',type(array3))
print('Array3 array 형태:',array3.shape)


Array1 type: <class 'numpy.ndarray'>
Array1 array 형태: (3,)
Array2 type: <class 'numpy.ndarray'>
Array2 array 형태: (2, 3)
Array3 type: <class 'numpy.ndarray'>
Array3 array 형태: (1, 3)


In [5]:
#ndim: 차원의 차수 반환
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [8]:
#dtype: 데이터 타입 반환
print(array1, array1.dtype)

[1 2 3] int64


In [11]:
test1 = [1,2,'test']
array4 = np.array(test1)
print(type(array4))
print(array4, array4.dtype)

test2 = [1,2,3.0]
array5 = np.array(test2)
print(type(array5))
print(array5,array5.dtype)

<class 'numpy.ndarray'>
['1' '2' 'test'] <U21
<class 'numpy.ndarray'>
[1. 2. 3.] float64


In [14]:
# astype(): 데이터 값의 타입 변환
array_int = np.array([1,2,3])
print('array_int')
print(array_int)
print(array_int.dtype)
print()

array_float = array_int.astype('float64')
print('array_float')
print(array_float.dtype)
print()

array_int1 = array_float.astype('int32')
print('array_int1')
print(array_int1.dtype)
print()

array_int
[1 2 3]
int64

array_float
float64

array_int1
int32



In [15]:
array_float1 = np.array([1.1, 2.1, 3.1])
print('array_float1')
print(array_float1)
print(array_float1.dtype)
print()

array_int2 = array_float1.astype('int64')
print('array_int2')
print(array_int2.dtype)
print()

array_float1
[1.1 2.1 3.1]
float64

array_int2
int64

