In [3]:
import numpy as np

#ndarray를 편리하게 생성하기
"""
arange(num): 0 ~ (num-1)의 값으로 순차적으로 ndarray의 값으로 변환
zeros(): tuple형태의 shape 값을 인자로 입력하면, 모든 값을 0으로 채운 해당 shape를 가진 ndarray로 반환
ones(): tuple형태의 shape 값을 인자로 입력하면, 모든 값을 1로 채운 해당 shape를 가진 ndarray로 반환
"""

sequence_array = np.arange(10)
zeros_array = np.zeros((3,2), dtype = 'int32')
ones_array = np.ones((3,2))

print('sequence_array')
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape,'\n')

print('zeros_array')
print(zeros_array)
print(zeros_array.dtype, zeros_array.shape,'\n')

print('ones_array')
print(ones_array)
print(ones_array.dtype, ones_array.shape,'\n')

sequence_array
[0 1 2 3 4 5 6 7 8 9]
int64 (10,) 

zeros_array
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

ones_array
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2) 



In [5]:
#reshape():  변하고싶은 차원,크기를 함수 인자로 주면 해당 인자에 맞는 ndarray로 변환


array1 = np.arange(10)
print('array1: ',array1,'\n')

array2 = array1.reshape(2,5)
print('array2:\n',array2,'\n')

array3 = array1.reshape(5,2)
print('array3:\n',array3,'\n')

"""
array4 = array1.reshape(4,3) 과 같이 지정된 사이즈로 변경이 불가능하면 오류 발생
"""



array1:  [0 1 2 3 4 5 6 7 8 9] 

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 



'\narray4 = array1.reshape(4,3) 과 같이 지정된 사이즈로 변경이 불가능하면 오류 발생\n'

In [8]:
#reshape() method에 인자로 -1 사용 -> ndarray와 호환되는 새로운 shape로 변환
array4 = np.arange(10)

array5 = array4.reshape(-1,5)
print('array5:\n')
print(array5)
print(array5.shape,'\n')

array6 = array4.reshape(5,-1)
print('array6:\n')
print(array6)
print(array6.shape,'\n')

"""
-1인자도 마찬가지로, array4.reshape(4,-1)과 같이 변경할 수 없는 값이 인자로 주어지면 에러 발생
"""

#tolist(): ndarray를 리스트 자료형으로 변환
print('array5:',array5.tolist(),'\n')

array5:

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5) 

array6:

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2) 

array5: [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]] 

